조건 다중회귀
- Feature 영향도
- test size = 0.1
- linear regression vs decision tree regressor
- regressor model 성능평가 MSE

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
df['target'] = diabetes.target
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [34]:
from sklearn.linear_model  import LinearRegression

y = diabetes.target
for feature in diabetes.feature_names: #반복문에서 i는 정수일때, name은 단수형으로 
    X = df[feature].values.reshape(-1,1)
    lr = LinearRegression()
    lr.fit(X,y)
    r2=lr.score(X,y)
    print(f'{feature}:{r2:.4f}')

age:0.0353
sex:0.0019
bmi:0.3439
bp:0.1949
s1:0.0450
s2:0.0303
s3:0.1559
s4:0.1853
s5:0.3202
s6:0.1463


In [35]:
X = diabetes.data
y = diabetes.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.1,random_state=2021
)
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [36]:
lr.score(X,y), lr.coef_, lr.intercept_

(0.5177494254132934,
 array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
        -792.18416163,  476.74583782,  101.04457032,  177.06417623,
         751.27932109,   67.62538639]),
 152.1334841628965)

In [37]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [38]:
np.dot(lr.coef_,diabetes.data[0]) + lr.intercept_

206.11706978709228

In [43]:
for i in range(5):
    pred = np.dot(lr.coef_,diabetes.data[i]) + lr.intercept_
    print(f'예측값:{pred:.2f}, 실제값:{diabetes.target[i]}')

예측값:206.12, 실제값:151.0
예측값:68.07, 실제값:75.0
예측값:176.88, 실제값:141.0
예측값:166.92, 실제값:206.0
예측값:128.46, 실제값:135.0


In [44]:
lr.predict(diabetes.data[:5])

array([206.11706979,  68.07234761, 176.88406035, 166.91796559,
       128.45984241])

In [22]:
pred1 = lr.predict(X_test)

In [23]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, pred1)
rmse = np.sqrt(mse) #Root mean squared error
mse, rmse

(2284.0679603143285, 47.79192358876475)

### decision tree regressor

In [24]:
from sklearn.tree  import DecisionTreeRegressor

y = diabetes.target
for feature in diabetes.feature_names: #반복문에서 i는 정수일때, name은 단수형으로 
    X = df[feature].values.reshape(-1,1)
    lr1 = DecisionTreeRegressor()
    lr1.fit(X,y)
    r2=lr1.score(X,y)
    print(f'{feature}:{r2:.4f}')

age:0.1409
sex:0.0019
bmi:0.5809
bp:0.3705
s1:0.3417
s2:0.7229
s3:0.2702
s4:0.3119
s5:0.5953
s6:0.2677


In [30]:
lr1.score(X,y)

0.2676745201817913

In [46]:
X = diabetes.data
y = diabetes.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.1,random_state=2021
)
lr2 = DecisionTreeRegressor()
lr2.fit(X,y)

DecisionTreeRegressor()

In [48]:
lr2.score(X,y)

1.0

In [49]:
lr2.predict(diabetes.data[:5])

array([151.,  75., 141., 206., 135.])