조건 다중회귀
- Feature 영향도
- test size = 0.1
- linear regression vs decision tree regressor
- regressor model 성능평가 MSE

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
df['target'] = diabetes.target
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [3]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [4]:
from sklearn.linear_model  import LinearRegression

y = diabetes.target
for feature in diabetes.feature_names: #반복문에서 i는 정수일때, name은 단수형으로 
    X = df[feature].values.reshape(-1,1)
    lr = LinearRegression()
    lr.fit(X,y)
    r2=lr.score(X,y)
    print(f'{feature}:{r2:.4f}')

age:0.0353
sex:0.0019
bmi:0.3439
bp:0.1949
s1:0.0450
s2:0.0303
s3:0.1559
s4:0.1853
s5:0.3202
s6:0.1463


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.1,random_state=2021
)
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [28]:
lr.score(X_test,y_test), lr.coef_, lr.intercept_

(0.4558401786089106,
 array([ -14.06014661, -246.92791992,  547.80956855,  286.58708365,
        -656.22582592,  364.21134557,   60.28474402,  182.53318837,
         702.08292875,   68.21197298]),
 151.67372554450927)

In [7]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [8]:
np.dot(lr.coef_,diabetes.data[0]) + lr.intercept_

206.11706978709228

In [9]:
for i in range(5):
    pred = np.dot(lr.coef_,diabetes.data[i]) + lr.intercept_
    print(f'예측값:{pred:.2f}, 실제값:{diabetes.target[i]}')

예측값:206.12, 실제값:151.0
예측값:68.07, 실제값:75.0
예측값:176.88, 실제값:141.0
예측값:166.92, 실제값:206.0
예측값:128.46, 실제값:135.0


In [10]:
lr.predict(diabetes.data[:5])

array([206.11706979,  68.07234761, 176.88406035, 166.91796559,
       128.45984241])

In [11]:
pred1 = lr.predict(X_test)

In [12]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, pred1)
rmse = np.sqrt(mse) #Root mean squared error
mse, rmse

(2284.0679603143285, 47.79192358876475)

### decision tree regressor

In [13]:
from sklearn.tree  import DecisionTreeRegressor

y = diabetes.target
for feature in diabetes.feature_names: #반복문에서 i는 정수일때, name은 단수형으로 
    X = df[feature].values.reshape(-1,1)
    lr1 = DecisionTreeRegressor()
    lr1.fit(X,y)
    r2=lr1.score(X,y)
    print(f'{feature}:{r2:.4f}')

age:0.1409
sex:0.0019
bmi:0.5809
bp:0.3705
s1:0.3417
s2:0.7229
s3:0.2702
s4:0.3119
s5:0.5953
s6:0.2677


In [14]:
lr1.score(X,y)

0.2676745201817913

In [15]:
X = diabetes.data
y = diabetes.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.1,random_state=2021
)
lr2 = DecisionTreeRegressor()
lr2.fit(X_train,y_train)

DecisionTreeRegressor()

In [19]:
lr2.score(X_test,y_test)

-0.5790133346998787

In [22]:
pred3=lr2.predict(X_test)
len(X_test)

45

In [23]:
for i in range(45):
    print(f'예측값:{pred3[i]:.2f}, 실제값:{y_test[i]}')

예측값:178.00, 실제값:155.0
예측값:118.00, 실제값:167.0
예측값:206.00, 실제값:185.0
예측값:190.00, 실제값:109.0
예측값:127.00, 실제값:65.0
예측값:47.00, 실제값:77.0
예측값:225.00, 실제값:277.0
예측값:145.00, 실제값:244.0
예측값:179.00, 실제값:148.0
예측값:214.00, 실제값:102.0
예측값:55.00, 실제값:200.0
예측값:214.00, 실제값:162.0
예측값:113.00, 실제값:59.0
예측값:210.00, 실제값:147.0
예측값:181.00, 실제값:216.0
예측값:150.00, 실제값:144.0
예측값:78.00, 실제값:85.0
예측값:150.00, 실제값:131.0
예측값:134.00, 실제값:196.0
예측값:235.00, 실제값:212.0
예측값:143.00, 실제값:60.0
예측값:48.00, 실제값:252.0
예측값:90.00, 실제값:121.0
예측값:63.00, 실제값:78.0
예측값:270.00, 실제값:275.0
예측값:281.00, 실제값:336.0
예측값:160.00, 실제값:190.0
예측값:78.00, 실제값:221.0
예측값:182.00, 실제값:103.0
예측값:151.00, 실제값:156.0
예측값:95.00, 실제값:235.0
예측값:168.00, 실제값:102.0
예측값:73.00, 실제값:115.0
예측값:48.00, 실제값:276.0
예측값:200.00, 실제값:140.0
예측값:97.00, 실제값:83.0
예측값:182.00, 실제값:95.0
예측값:281.00, 실제값:151.0
예측값:78.00, 실제값:141.0
예측값:242.00, 실제값:128.0
예측값:272.00, 실제값:217.0
예측값:293.00, 실제값:170.0
예측값:140.00, 실제값:110.0
예측값:96.00, 실제값:191.0
예측값:63.00, 실제값:91.0


In [24]:
from sklearn.metrics import r2_score  # R squared - 성능 평가 요소
r2_score(y_test, pred3)  

-0.5790133346998787

In [25]:
from  sklearn.metrics import mean_squared_error        #MSE성능평가
mse = mean_squared_error(y_test, pred3)
rmse = np.sqrt(mse)             #Root mean squared error
mse, rmse  

(6877.711111111111, 82.93196676258866)

In [31]:
rse = pd.DataFrame({'ytest':y_test, 'lr':pred1, 'dtr':pred3})
rse

ytest          lr    dtr
0   155.0  157.936368  178.0
1   167.0  184.066094  118.0
2   185.0  164.676050  206.0
3   109.0  156.810879  190.0
4    65.0   78.371948  127.0
5    77.0   62.000775   47.0
6   277.0  178.262282  225.0
7   244.0  178.704429  145.0
8   148.0  132.174667  179.0
9   102.0   87.666241  214.0
10  200.0  179.155702   55.0
11  162.0  125.040384  214.0
12   59.0  121.860737  113.0
13  147.0  174.888578  210.0
14  216.0  170.655554  181.0
15  144.0  122.957734  150.0
16   85.0  152.827066   78.0
17  131.0  157.014898  150.0
18  196.0  164.166695  134.0
19  212.0  191.905938  235.0
20   60.0   80.482004  143.0
21  252.0  153.683699   48.0
22  121.0  169.231618   90.0
23   78.0   53.042594   63.0
24  275.0  251.358983  270.0
25  336.0  254.919863  281.0
26  190.0  142.601471  160.0
27  221.0  202.494585   78.0
28  103.0  129.832641  182.0
29  156.0  159.938920  151.0
30  235.0  170.440632   95.0
31  102.0  111.446229  168.0
32  115.0  138.356597   73.0
33  276.0  157.876860   48.0
34  140.0  128.827255  200.0
35   83.0  123.834771   97.0
36   95.0  152.758563  182.0
37  151.0  206.117070  281.0
38  141.0  176.884060   78.0
39  128.0  228.661008  242.0
40  217.0  231.292662  272.0
41  170.0  191.166744  293.0
42  110.0  158.810331  140.0
43  191.0  125.276977   96.0
44   91.0   91.202856   63.0