# 여기는 모두 필수 암기 필요

In [47]:
import pandas as pd

In [48]:
with open('pima-indians-diabetes.csv') as file:
    words=file.read()

In [49]:
# df=pd.read_csv('pima-indians-diabetes.csv', skiprows=9, header=None)
#헤더 논으로 둬서 임시로 열 생성

In [50]:
df=pd.read_csv('pima-indians-diabetes.csv', skiprows=9)
df

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [51]:
columns = ['Number of times pregnant','Plasma glucose concentration a 2 hours in an oral glucose tolerance test'
, 'Diastolic blood pressure (mm Hg)','Triceps skin fold thickness (mm)',
'2-Hour serum insulin (mu U/ml)','Body mass index (weight in kg/(height in m)^2)',
'Diabetes pedigree function','Age (years)','Class variable (0 or 1)']

In [52]:
df2=pd.DataFrame(df.values, columns=columns)
df2

Number of times pregnant  \
0                         1.0   
1                         8.0   
2                         1.0   
3                         0.0   
4                         5.0   
..                        ...   
762                      10.0   
763                       2.0   
764                       5.0   
765                       1.0   
766                       1.0   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                 85.0                          
1                                                183.0                          
2                                                 89.0                          
3                                                137.0                          
4                                                116.0                          
..                                                 ...                          
762                                              101.0                          
763                                              122.0                          
764                                              121.0                          
765                                              126.0                          
766                                               93.0                          

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                66.0                              29.0   
1                                64.0                               0.0   
2                                66.0                              23.0   
3                                40.0                              35.0   
4                                74.0                               0.0   
..                                ...                               ...   
762                              76.0                              48.0   
763                              70.0                              27.0   
764                              72.0                              23.0   
765                              60.0                               0.0   
766                              70.0                              31.0   

     2-Hour serum insulin (mu U/ml)  \
0                               0.0   
1                               0.0   
2                              94.0   
3                             168.0   
4                               0.0   
..                              ...   
762                           180.0   
763                             0.0   
764                           112.0   
765                             0.0   
766                             0.0   

     Body mass index (weight in kg/(height in m)^2)  \
0                                              26.6   
1                                              23.3   
2                                              28.1   
3                                              43.1   
4                                              25.6   
..                                              ...   
762                                            32.9   
763                                            36.8   
764                                            26.2   
765                                            30.1   
766                                            30.4   

     Diabetes pedigree function  Age (years)  Class variable (0 or 1)  
0                         0.351         31.0                      0.0  
1                         0.672         32.0                      1.0  
2                         0.167         21.0                      0.0  
3                         2.288         33.0                      1.0  
4                         0.201         30.0                      0.0  
..                          ...          ...                      ...  
762                       0.171         63.0                      0.0  
763                       0.

In [53]:
new_data = {
    'Number of times pregnant' : 6.000,
    'Plasma glucose concentration a 2 hours in an oral glucose tolerance test' : 148.000,
    'Diastolic blood pressure (mm Hg)' : 72.000,
    'Triceps skin fold thickness (mm)' : 35.000,
    '2-Hour serum insulin (mu U/ml)' : 0.000,
    'Body mass index (weight in kg/(height in m)^2)' : 33.600,
    'Diabetes pedigree function' : 0.627,
    'Age (years)' : 50.000,
    'Class variable (0 or 1)' : 1.000
}
 
idx = 0 ## 원하는 인덱스
 
temp1 = df2[df2.index < idx]
temp2 = df2[df2.index >= idx]
df2 = temp1.append(new_data,ignore_index=True).append(temp2, ignore_index=True)

In [54]:
df2

Number of times pregnant  \
0                         6.0   
1                         1.0   
2                         8.0   
3                         1.0   
4                         0.0   
..                        ...   
763                      10.0   
764                       2.0   
765                       5.0   
766                       1.0   
767                       1.0   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148.0                          
1                                                 85.0                          
2                                                183.0                          
3                                                 89.0                          
4                                                137.0                          
..                                                 ...                          
763                                              101.0                          
764                                              122.0                          
765                                              121.0                          
766                                              126.0                          
767                                               93.0                          

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72.0                              35.0   
1                                66.0                              29.0   
2                                64.0                               0.0   
3                                66.0                              23.0   
4                                40.0                              35.0   
..                                ...                               ...   
763                              76.0                              48.0   
764                              70.0                              27.0   
765                              72.0                              23.0   
766                              60.0                               0.0   
767                              70.0                              31.0   

     2-Hour serum insulin (mu U/ml)  \
0                               0.0   
1                               0.0   
2                               0.0   
3                              94.0   
4                             168.0   
..                              ...   
763                           180.0   
764                             0.0   
765                           112.0   
766                             0.0   
767                             0.0   

     Body mass index (weight in kg/(height in m)^2)  \
0                                              33.6   
1                                              26.6   
2                                              23.3   
3                                              28.1   
4                                              43.1   
..                                              ...   
763                                            32.9   
764                                            36.8   
765                                            26.2   
766                                            30.1   
767                                            30.4   

     Diabetes pedigree function  Age (years)  Class variable (0 or 1)  
0                         0.627         50.0                      1.0  
1                         0.351         31.0                      0.0  
2                         0.672         32.0                      1.0  
3                         0.167         21.0                      0.0  
4                         2.288         33.0                      1.0  
..                          ...          ...                      ...  
763                       0.171         63.0                      0.0  
764                       0.

In [55]:
# 어떤 값이 몇개나 있는지 확인
df2['Class variable (0 or 1)'].value_counts() #데이터프레임
# np.unique(df2['Class variable (0 or 1)'], return_counts=True) # 넘파이

0.0    500
1.0    268
Name: Class variable (0 or 1), dtype: int64

In [56]:
df2['Number of times pregnant'].values

array([ 6.,  1.,  8.,  1.,  0.,  5.,  3., 10.,  2.,  8.,  4., 10., 10.,
        1.,  5.,  7.,  0.,  7.,  1.,  1.,  3.,  8.,  7.,  9., 11., 10.,
        7.,  1., 13.,  5.,  5.,  3.,  3.,  6., 10.,  4., 11.,  9.,  2.,
        4.,  3.,  7.,  7.,  9.,  7.,  0.,  1.,  2.,  7.,  7.,  1.,  1.,
        5.,  8.,  7.,  1.,  7.,  0.,  0.,  0.,  2.,  8.,  5.,  2.,  7.,
        5.,  0.,  2.,  1.,  4.,  2.,  5., 13.,  4.,  1.,  1.,  7.,  5.,
        0.,  2.,  3.,  2.,  7.,  0.,  5.,  2., 13.,  2., 15.,  1.,  1.,
        4.,  7.,  4.,  2.,  6.,  2.,  1.,  6.,  1.,  1.,  1.,  0.,  1.,
        2.,  1.,  1.,  4.,  3.,  0.,  3.,  8.,  1.,  4.,  7.,  4.,  5.,
        5.,  4.,  4.,  0.,  6.,  2.,  5.,  0.,  1.,  3.,  1.,  1.,  0.,
        4.,  9.,  3.,  8.,  2.,  2.,  0.,  0.,  0.,  5.,  3.,  5.,  2.,
       10.,  4.,  0.,  9.,  2.,  5.,  2.,  1.,  4.,  9.,  1.,  8.,  7.,
        2.,  1.,  2., 17.,  4.,  7.,  0.,  2.,  0.,  6.,  3.,  4.,  4.,
        3.,  6.,  6.,  2.,  1.,  2.,  8.,  6.,  0.,  5.,  5.,  6

In [57]:
df2.iloc[:,:-1].values

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [58]:
df2=pd.DataFrame(df.values, columns=columns)
df2.loc[0]

Number of times pregnant                                                     1.000
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    85.000
Diastolic blood pressure (mm Hg)                                            66.000
Triceps skin fold thickness (mm)                                            29.000
2-Hour serum insulin (mu U/ml)                                               0.000
Body mass index (weight in kg/(height in m)^2)                              26.600
Diabetes pedigree function                                                   0.351
Age (years)                                                                 31.000
Class variable (0 or 1)                                                      0.000
Name: 0, dtype: float64

In [59]:
df2.iloc[:,:-1].values #.values는 넘파이 데이터로 치환해줌

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 2.33e+01, 6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.62e+01, 2.45e-01, 3.00e+01],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.01e+01, 3.49e-01, 4.70e+01],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.04e+01, 3.15e-01, 2.30e+01]])

In [60]:
# 사이킷 런을 배열형식을 넘파이, 데이터프레임 둘다 지원함
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df2.iloc[:,:-1], df2['Class variable (0 or 1)'], random_state=2021, 
    test_size=0.2, stratify=df2['Class variable (0 or 1)']
) ## test_size는 랜덤군을 80% 실제 군을 20% 조정, stratify는 당뇨인지 아닌지 정해져있는 열의 결과값 비율을 랜덤집군과 실제집군에 나눠주는 조건

In [61]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((613, 8), (154, 8), (613,), (154,))

In [62]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [63]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

In [64]:
pred = dtc.predict(X_test)

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.6428571428571429

In [66]:
from sklearn.model_selection import GridSearchCV

In [67]:
params = {
    'max_depth' : [2,3,4,5,6],

    'min_samples_split' : [2,3,4]
}

In [68]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [69]:
grid_dt.best_score_

0.7194723417822414

In [70]:
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 2}

In [71]:
best_dt=grid_dt.best_estimator_

In [72]:
best_dt.score(X_test, y_test)

0.7402597402597403

# 실제값 하나가 주어졌을 떄 당뇨병 유무를 확인하는 방법

In [83]:
y_test.values[33]

0.0

In [88]:
test_data=X_test.values[33]
test_data

array([  0.   , 126.   ,  86.   ,  27.   , 120.   ,  27.4  ,   0.515,
        21.   ])

In [91]:
# x_test형태를 y_test형태인 8,로 바꿔줘야 가능
best_dt.predict(test_data.reshape(1,8))

array([0.])